
import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UiContextProvider } from '../contexts/UiContext'
import { UserContextProvider } from '../contexts/UserContext'
import Header from '@/src/components/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "O'Galerie",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <UserContextProvider>
      <UiContextProvider>
        <body className={`${inter.className} flex flex-col`}>          
          <Header />
          {children}         
        </body>
      </UiContextProvider>
      </UserContextProvider>
    </html>
  )
}
